- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 18000 # DeltaV - 5 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 # DeltaV - 5 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # DeltaV - 5 hours
    - !type:DepartmentTimeRequirement # DeltaV - Epistemics dept time requirement
      department: Science
      time: 18000 # 5 hours
#    - !type:DepartmentTimeRequirement
#      department: Command
#      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement # DeltaV - Civilian dept time requirement
      department: Civilian
      time: 10800 # 3 hours
    - !type:OverallPlaytimeRequirement # DeltaV - Playtime requirement
      time: 72000 # 20 hours
  weight: 20
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the captain instead.
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Cargo
  - Atmospherics
  - Medical

- type: startingGear
  id: HoPGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackHOPFilled
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatHopcap
    id: HoPPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelHOPFilled
  duffelbag: ClothingBackpackDuffelHOPFilled
