- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 43200 # DeltaV - 12 hours
    - !type:OverallPlaytimeRequirement
      time: 72000 # DeltaV - 20 hours
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatRnd
    id: RnDPDA
    ears: ClothingHeadsetRD
  innerclothingskirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled
