- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 21600 # 6 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 4 hrs
  startingGear: BrigmedicGearDeltaV
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGearDeltaV # see Prototypes/Roles/Jobs/Fun/misc_startinggear.yml for "BrigmedicGear"
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecBlue
    outerClothing: ClothingOuterArmorPlateCarrier
    back: ClothingBackpackBrigmedicDeltaVFilled
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretSecurity
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtSecBlue
  satchel: ClothingBackpackSatchelBrigmedicDeltaVFilled
  duffelbag: ClothingBackpackDuffelBrigmedicDeltaVFilled
